# Generated by Django 3.2.12 on 2022-03-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_drone_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='drone_carrier',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='medications',
        ),
        migrations.AddField(
            model_name='drone',
            name='medications',
            field=models.ManyToManyField(to='api.Medication'),
        ),
    ]
