# Generated by Django 3.2.12 on 2022-03-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220305_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='medications',
            field=models.ManyToManyField(null=True, to='api.Medication'),
        ),
    ]
