# Generated by Django 3.2.12 on 2022-03-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_drone_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='model',
            field=models.PositiveSmallIntegerField(choices=[('LI', 'Ligthweight'), ('MI', 'Middleweight'), ('CR', 'Cruiseweight'), ('HW', 'Heavyweight')], default='LI', help_text='The model type of the drone'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[('ID', 'IDLE'), ('LA', 'LOADING'), ('LO', 'LOADED'), ('DI', 'DELIVERING'), ('DE', 'DELIVERED'), ('RE', 'RETURNING')], default='ID', help_text='The current state of the drone'),
        ),
    ]
