# Generated by Django 3.2.12 on 2022-03-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220306_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='model',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Ligthweight'), ('2', 'Middleweight'), ('3', 'Cruiseweight'), ('4', 'Heavyweight')], default='1', help_text='The model type of the drone'),
        ),
    ]
