# Generated by Django 3.2.12 on 2022-03-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_drone_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='model',
            field=models.PositiveSmallIntegerField(choices=[('LI', 'Ligthweight'), ('MI', 'Middleweight'), ('CR', 'Cruiseweight'), ('HW', 'Heavyweight')], default='LI', help_text='The model type of the drone'),
        ),
    ]
