# Generated by Django 3.2.12 on 2022-02-28 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('model', models.CharField(choices=[('L', 'Lightweight'), ('M', 'Middleweight'), ('C', 'Cruiseweight'), ('H', 'Heavyweight')], default='L', max_length=2)),
                ('state', models.CharField(choices=[('I', 'IDLE'), ('LG', 'LOADING'), ('LE', 'LOADED'), ('DG', 'DELIVERING'), ('DE', 'DELIVERED'), ('RG', 'RETURNING')], default='I', max_length=2)),
                ('drone_id', models.IntegerField(help_text='The id for drones in the database', primary_key=True, serialize=False)),
                ('serial_number', models.CharField(help_text='The serial number of the drones', max_length=100, unique=True)),
                ('weight_limit', models.IntegerField(help_text='The weight limit that a dron can carry', validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('battery_capacity', models.IntegerField(help_text='The percent capacity of the battery', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
